CREATE TABLE IF NOT EXISTS income (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_email VARCHAR(255) NOT NULL,
  source VARCHAR(120) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  cadence VARCHAR(50) DEFAULT 'monthly',
  date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);